### ISSUE TITLE
I am getting error at genetic_algorithm import

### ISSUE THREAD

**Issue by ravichaurasia** [darolt/wsn#6]
return importlib.import_module('_genetic_algorithm')
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

This is the error which iam getting, is it due to python version because I am using python 3x version

**Comment by HenryChen1** [comment]
I can't get the specific error  from your discription. Maybe you can put up the whole error message.😂
Or you can refer to my example. I fixed some problems and run on PYTHON 3.7 and Window 10 [portal->](https://github.com/HenryChen1/wsn) (This is an incomplete version. )

I hope it works for you. 😀

**Comment by ravichaurasia** [comment]
C:\ProgramData\Anaconda3\envs\wsn-master\Scripts\python.exe D:/VT/code/wsn-master_NEW/wsn-master/run.py
Traceback (most recent call last):
  File "D:/VT/code/wsn-master_NEW/wsn-master/run.py", line 6, in <module>
    from python.network.network import Network
  File "D:\VT\code\wsn-master_NEW\wsn-master\python\network\network.py", line 8, in <module>
    from python.sleep_scheduling.sleep_scheduler import *
  File "D:\VT\code\wsn-master_NEW\wsn-master\python\sleep_scheduling\sleep_scheduler.py", line 9, in <module>
    from cc.genetic_algorithm import *
  File "D:\VT\code\wsn-master_NEW\wsn-master\cc\genetic_algorithm.py", line 13, in <module>
    from . import _genetic_algorithm
ImportError: cannot import name '_genetic_algorithm'

Again I am getting the same error

**Comment by HenryChen1** [comment]
I think you probably haven't compiled the C/C++ file yet (via SWIG)😮
Follow step 2 below.
![image](https://user-images.githubusercontent.com/24852788/75518316-9229ba80-5a3b-11ea-9251-a86687287306.png)

**Comment by Opdoop** [comment]
Build Precondition: 
1. Install SWIG
2. Using python=2.7
3. Change setup.py `os.environ["CC"] = "g++-5 -std=c++11` to your version
4. Change setup.py `build_path` to your path

And here you go: 
run `python setup.py build_ext --inplace` **successfully** 🎉
run `python run.py`
